# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
    - id: mypy
      args: [
        --install-types,
        --non-interactive,
        --no-strict-optional,
        --ignore-missing-imports,
      ]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    - id: pyupgrade
      args: [--py38-plus]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        exclude: conda/meta.yaml
      - id: debug-statements
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
